---
layout: episode
episode: 226
title: "Episode 226 — Interview - Про умные машинки"
category: interview
guests: abashev, vlasova
---

== РЕКЛАМА

Как решать глобальные задачи, не уезжая из родного города
Возможно ли заниматься международными IT-проектами из дома и построить серьёзную карьеру, не покидая родного города?

В Luxoft можно! В Luxoft нанимают специалистов во всех регионах России. Стать ведущим программистом, аналитиком, тестировщиком, project-менеджером в крупных международных проектах, не покидая родного города стало очень просто.

Найти вакансию своей мечты и порекомендовать подходящего человека всегда можно на сайте http://career.luxoft.com/job-opportunities/?keyword=&country%5B%5D=russian%2Bfederation&city%5B%5D=remote%2Brussia&specialization=&set_filter=Y&utm_source=podcast&utm_medium=post&utm_campaign=20210402_b2e_wfa-ru


== Гости и участники

* https://t.me/razborfeed[@a_abashev]
* https://www.facebook.com/vlasaleksa/[Александра Власова]

== Темы

* Автомобильное программное обеспечение в целом
* Что из себя представляет тестирование в Automotive
* Платформы менеджмента данных в automotive: зачем они и какие технологии в них применяются
