---
layout: episode
episode: 227
title: "Episode 227 — Interview - Зачем внедрять DevOps"
category: interview
guests: abashev, seleznev
---

== РЕКЛАМА

Как решать глобальные задачи, не уезжая из родного города
Возможно ли заниматься международными IT-проектами из дома и построить серьёзную карьеру, не покидая родного города?

В Luxoft можно! В Luxoft нанимают специалистов во всех регионах России. Стать ведущим программистом, аналитиком, тестировщиком, project-менеджером в крупных международных проектах, не покидая родного города стало очень просто.

Найти вакансию своей мечты и порекомендовать подходящего человека всегда можно на сайте http://career.luxoft.com/job-opportunities/?keyword=&country%5B%5D=russian%2Bfederation&city%5B%5D=remote%2Brussia&specialization=&set_filter=Y&utm_source=podcast&utm_medium=post&utm_campaign=20210402_b2e_wfa-ru


== Гости и участники

* https://t.me/razborfeed[@a_abashev]
* Александр Селезнев


== Темы

* Чем отличается девопс в продуктовой команде от аутсорсной?
* Нужен ли вам девопс если ваш заказчик - вотерфольный энтерпрайз?
* Помогает ли девопс в разовых и коротких проектах?
* Сколько денег и крови стоит внедрить девопс?
