---
layout: episode
episode: 248
title: "Episode 248 — Classic - Новая идея"
category: classic
guests: abashev, golodnyj, antonarhipov
---

Самая крупная конференция-практикум для тимлидов и руководителей💥

2000 участников | 70+ докладов | 11 воркшопов | 6 круглых столов

Территория TeamLead — это энергия тысячи менеджеров и тимлидов, расширение кругозора, отработка навыков на мастер-классах, участие в круглых столах и много-много нетворкинга. Только в 2022 году — 2 трека по управлению знаниями от создателей Knowledge Conf.
Программа конференции построена так, что каждый участник сможет найти лекарство от своей боли — и тимлид небольшого стартапа, и опытный СТО крупной компании. Такая концентрация тимлидского опыта на человеко-час и квадратный метр бывает в Москве только один раз в год. Не пропустите!

🔹Каждый доклад — решение конкретной задачи.
🔹Вдохновляющие идеи и решения.
🔹Связи, на которые ушли бы годы
🔹Программа на основе трендов самого большого сообщества тимлидов.
🔹Спикеры не только IT индустрии

17-18 мая 2022
Москва. Крокус-Экспо

Скидка 10% по промокоду TLPODCAST
Забронировать билет|Смотреть программу 👇
https://clck.ru/asjKY[Забронировать билет|Смотреть программу 👇]

== Гости и участники

* https://twitter.com/antonarhipov[@antonarhipov]
* https://t.me/razborfeed[@abashev]
* https://twitter.com/golodnyj[Антон Черноусов]

== Темы

* https://blog.jetbrains.com/idea/2022/04/intellij-idea-2022-1/
* https://github.blog/2022-04-12-git-security-vulnerability-announced/
* https://www.atlassian.com/engineering/april-2022-outage-update
