---
layout: episode
episode: 246
title: "Episode 246 — Interview - Распределённые БД"
category: interview
guests: abashev, golodnyj, ozerov, goncharuk
---

7 и 18 марта 2022 года в Москве состоится крупнейшая в Европе IT-конференция HighLoad++ Foundation

🔥В программе — более 130 докладов, каждый из которых решает конкретную задачу. Но конференция — это не только доклады.

На HighLoad++ Foundation вы легко сможете пообщаться с ТОПами IT-индустрии и найти ответы на свои вопросы. А хотите получить персональную консультацию от разработчиков технологий, на которых построен ваш проект? Приходите! Что ещё? Узнаете, как устроены Яндекс, VK, Avito, Mail.ru, Tinkoff и другие крупные проекты. 

😎Влиться в профессиональное комьюнити, завязать полезные знакомства, обновить свою базу знаний и найти решение для сложных задач — всё это на одной площадке.

Приходите на HighLoad++ Foundation! 17 и 18 марта, Москва.

Скидка 10% по промокоду FOUNDATION

https://clck.ru/asjU7[Забронировать билет|Смотреть программу 👇]


== Гости и участники

* https://twitter.com/devozerov[Владимир Озеров]
* https://www.querifylabs.com/[Алексей Гончарюк]
* https://t.me/razborfeed[@abashev]
* https://twitter.com/golodnyj[Антон Черноусов]
